
package com.xwtech.xwecp.communication.ws.lableInfoClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QueryLableServiceImplService", targetNamespace = "http://service.labservice.service.nubass.newland.com/", wsdlLocation = "http://10.32.233.48:8200/nlisb/ws/lableService?wsdl")
public class QueryLableServiceImplService
    extends Service
{

    private final static URL QUERYLABLESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xwtech.xwecp.communication.ws.lableInfoClient.QueryLableServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xwtech.xwecp.communication.ws.lableInfoClient.QueryLableServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://10.32.233.48:8200/nlisb/ws/lableService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.32.233.48:8200/nlisb/ws/lableService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERYLABLESERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public QueryLableServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryLableServiceImplService() {
        super(QUERYLABLESERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.labservice.service.nubass.newland.com/", "QueryLableServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns QueryLableService
     */
    @WebEndpoint(name = "QueryLableServiceImplPort")
    public QueryLableService getQueryLableServiceImplPort() {
        return super.getPort(new QName("http://service.labservice.service.nubass.newland.com/", "QueryLableServiceImplPort"), QueryLableService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryLableService
     */
    @WebEndpoint(name = "QueryLableServiceImplPort")
    public QueryLableService getQueryLableServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.labservice.service.nubass.newland.com/", "QueryLableServiceImplPort"), QueryLableService.class, features);
    }

}
