
package com.xwtech.xwecp.communication.ws.gsmClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SerialServerImplService", targetNamespace = "http://service.serial.service.nubass.newland.com/", wsdlLocation = "http://10.32.233.48:8200/nlisb/ws/SerialServer?wsdl")
public class SerialServerImplService
    extends Service
{

    private final static URL SERIALSERVERIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SerialServerImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = SerialServerImplService.class.getResource(".");
            url = new URL(baseUrl, "http://10.32.233.48:8200/nlisb/ws/SerialServer?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.32.233.48:8200/nlisb/ws/SerialServer?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERIALSERVERIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SerialServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SerialServerImplService() {
        super(SERIALSERVERIMPLSERVICE_WSDL_LOCATION, new QName("http://service.serial.service.nubass.newland.com/", "SerialServerImplService"));
    }

    /**
     * 
     * @return
     *     returns SerialServer
     */
    @WebEndpoint(name = "SerialServerImplPort")
    public SerialServer getSerialServerImplPort() {
        return super.getPort(new QName("http://service.serial.service.nubass.newland.com/", "SerialServerImplPort"), SerialServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SerialServer
     */
    @WebEndpoint(name = "SerialServerImplPort")
    public SerialServer getSerialServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.serial.service.nubass.newland.com/", "SerialServerImplPort"), SerialServer.class, features);
    }

}
