
package com.xwtech.xwecp.communication.ws.gsmClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SerialServer", targetNamespace = "http://service.serial.service.nubass.newland.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SerialServer {


    /**
     * 
     * @param message
     * @return
     *     returns com.newland.client.ResponseObject
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "querySms", targetNamespace = "http://service.serial.service.nubass.newland.com/", className = "com.newland.client.QuerySms")
    @ResponseWrapper(localName = "querySmsResponse", targetNamespace = "http://service.serial.service.nubass.newland.com/", className = "com.newland.client.QuerySmsResponse")
    public ResponseObject querySms(
        @WebParam(name = "message", targetNamespace = "")
        RequestObject message);

    /**
     * 
     * @param message
     * @return
     *     returns com.newland.client.ResponseObject
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "queryGsm", targetNamespace = "http://service.serial.service.nubass.newland.com/", className = "com.newland.client.QueryGsm")
    @ResponseWrapper(localName = "queryGsmResponse", targetNamespace = "http://service.serial.service.nubass.newland.com/", className = "com.newland.client.QueryGsmResponse")
    public ResponseObject queryGsm(
        @WebParam(name = "message", targetNamespace = "")
        RequestObject message);

}
