
package com.xwtech.xwecp.communication.ws.lableInfoClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryLableService", targetNamespace = "http://service.labservice.service.nubass.newland.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryLableService {


    /**
     * 
     * @param message
     * @return
     *     returns com.wsclient.ResponseObject
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "queryLable", targetNamespace = "http://service.labservice.service.nubass.newland.com/", className = "com.wsclient.QueryLable")
    @ResponseWrapper(localName = "queryLableResponse", targetNamespace = "http://service.labservice.service.nubass.newland.com/", className = "com.wsclient.QueryLableResponse")
    public ResponseObject queryLable(
        @WebParam(name = "message", targetNamespace = "")
        RequestObject message);

}
